# permissions for end users to edit myoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: myoperator-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: d
    app.kubernetes.io/part-of: d
    app.kubernetes.io/managed-by: kustomize
  name: myoperator-editor-role
rules:
- apiGroups:
  - api.swastik.online
  resources:
  - myoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.swastik.online
  resources:
  - myoperators/status
  verbs:
  - get
